// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointOS.Data;

#nullable disable

namespace PointOS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504135914_initialCreated")]
    partial class initialCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PointOS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Our computers and tablets include all the big brands.",
                            Image = "/media/categories/computers.png",
                            Name = "Computers",
                            Type = "Automated"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Our range of watches are perfect whether you're looking to upgrade",
                            Image = "/media/categories/watches.png",
                            Name = "Watches",
                            Type = "Automated"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Our big range of headphones makes it easy to upgrade your device at a great price.",
                            Image = "/media/categories/headphones.png",
                            Name = "Headphones",
                            Type = "Manual"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Whatever your activity needs are, we've got you covered.",
                            Image = "/media/categories/footwear.png",
                            Name = "Footwear",
                            Type = "Automated"
                        });
                });

            modelBuilder.Entity("PointOS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StockStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Product 1",
                            Price = 229.00m,
                            Quantity = 50,
                            Rating = 3,
                            SKU = "02743005",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Product 2",
                            Price = 159.00m,
                            Quantity = 44,
                            Rating = 4,
                            SKU = "03961008",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "Product 3",
                            Price = 21.00m,
                            Quantity = 30,
                            Rating = 4,
                            SKU = "03819003",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Name = "Product 4",
                            Price = 159.00m,
                            Quantity = 43,
                            Rating = 4,
                            SKU = "03605007",
                            Status = "Published"
                        });
                });

            modelBuilder.Entity("PointOS.Models.Product", b =>
                {
                    b.HasOne("PointOS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PointOS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
